#Connexion \uFFFD la base de donn\uFFFDes
spring.datasource.url=jdbc:sqlserver://localhost;databasename=Projet_Spring;integratedSecurity=false;encrypt=false;trustServerCertificate=false
spring.datasource.username=sa
spring.datasource.password=sasa
spring.messages.encoding=UTF-8
#D\uFFFDtail des requ\uFFFDtes pour le d\uFFFDveloppement
logging.level.org.springframework.jdbc.core=TRACE