#Connexion \uFFFD la base de donn\uFFFDes
spring.datasource.url=jdbc:sqlserver://localhost;databasename=Projet_Spring;integratedSecurity=false;encrypt=false;trustServerCertificate=false
spring.datasource.username=sa
spring.datasource.password=sasa
spring.messages.encoding=UTF-8
#D\uFFFDtail des requ\uFFFDtes pour le d\uFFFDveloppement
logging.level.org.springframework.jdbc.core=TRACE
logging.level.fr.eni.enchere=DEBUG
server.port=8081
upload.path=src/main/resources/static/images/uploads

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.thymeleaf.cache=false
